const actions = {
    COUNTER_INCREMENT:"COUNTER_INCREMENT",
    COUNTER_DECREMENT: "COUNTER_DECREMENT",
    INFO_CHANGETEXT: "INFO_CHANGETEXT",
    FRUITS_ADD: "FRUITS_ADD"
};

export default actions;